/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.PemesananCtrl;
import java.awt.event.KeyEvent;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Well's-Comp
 */
public class PemesananBahanPustaka extends javax.swing.JFrame {
    private static PemesananCtrl C;

    /**
     * Creates new form PemesananBahanPustaka
     */
    public PemesananBahanPustaka() {
        initComponents();
        
        C = new PemesananCtrl();
        
        clear();
        setForm();
    }

    ///////////////////////////////METHOD-METHOD////////////////////////////////
    private void setForm()
    {
        this.setTitle("PENGECEKAN KETERSEDIAAN "
                + "DAN CETAK SURAT PEMESANAN BAHAN PUSTAKA");
        
        setTableDataBhnPustaka();
        setTableDataUsulanVerified();
        
        setTableUsulan();
        setTableBahanPustaka();
    }
    
    private void clear()
    {
        tableUsulan.clearSelection();
        tableBahanPustaka.clearSelection();
        
        
    }
    
    private void setTableUsulan()
    {
        for(int i = 0; i < tableUsulan.getColumnCount(); i++)
        {
            Class<?> column = tableUsulan.getColumnClass(i);
            tableUsulan.setDefaultEditor(column, null);
        }
        
        tableUsulan.getTableHeader().setReorderingAllowed(false);
        
        tableUsulan.setRowSelectionAllowed(false);
        tableUsulan.setColumnSelectionAllowed(false);
        tableUsulan.setCellSelectionEnabled(true);
        
        tableUsulan.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableUsulan.setDragEnabled(false);
        tableUsulan.setShowGrid(true);
        
        tableUsulan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void setTableBahanPustaka()
    {
        for(int i = 0; i < tableBahanPustaka.getColumnCount(); i++)
        {
            Class<?> column = tableBahanPustaka.getColumnClass(i);
            tableBahanPustaka.setDefaultEditor(column, null);
        }
        
        tableBahanPustaka.getTableHeader().setReorderingAllowed(false);
        
        tableBahanPustaka.setRowSelectionAllowed(false);
        tableBahanPustaka.setColumnSelectionAllowed(false);
        tableBahanPustaka.setCellSelectionEnabled(true);
        
        tableBahanPustaka.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableBahanPustaka.setDragEnabled(false);
        tableBahanPustaka.setShowGrid(true);
        
        tableBahanPustaka.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void setTableDataBhnPustaka()
    {
        tableBahanPustaka.setModel(C.getTableDataBahanPustaka());
    }
    
    private void setTableDataUsulanVerified()
    {
        tableUsulan.setModel(C.getTableDataUsulan());
    }
    ///////////////////////////////METHOD-METHOD////////////////////////////////

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtJudulUsulan = new javax.swing.JTextField();
        btnCariUsulan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsulan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtJudulBahanPustaka = new javax.swing.JTextField();
        btnCariBahanPustaka = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBahanPustaka = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PENGECEKAN KETERSEDIAAN BAHAN PUSTAKA DAN CETAK SURAT PEMESANAN BAHAN PUSTAKA");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(505, 400));

        jLabel3.setText("JUDUL BUKU");

        txtJudulUsulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJudulUsulanKeyPressed(evt);
            }
        });

        btnCariUsulan.setText("CARI");
        btnCariUsulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariUsulanActionPerformed(evt);
            }
        });
        btnCariUsulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariUsulanKeyPressed(evt);
            }
        });

        tableUsulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUsulan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJudulUsulan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariUsulan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudulUsulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariUsulan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("JUDUL BUKU");

        txtJudulBahanPustaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJudulBahanPustakaKeyPressed(evt);
            }
        });

        btnCariBahanPustaka.setText("CARI");
        btnCariBahanPustaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBahanPustakaActionPerformed(evt);
            }
        });
        btnCariBahanPustaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariBahanPustakaKeyPressed(evt);
            }
        });

        tableBahanPustaka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableBahanPustaka);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJudulBahanPustaka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBahanPustaka)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJudulBahanPustaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBahanPustaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("DAFTAR USULAN BAHAN PUSTAKA TERVERIFIKASI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("DAFTAR BAHAN PUSTAKA");

        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        btnCetak.setText("CETAK PEMESANAN");
        btnCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCetakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCetakMouseExited(evt);
            }
        });
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        btnCetak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCetakKeyPressed(evt);
            }
        });

        btnSelesai.setText("SELESAI");
        btnSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseExited(evt);
            }
        });
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        btnSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelesaiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelesai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCetak, btnHapus, btnSelesai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnCetak)
                    .addComponent(btnSelesai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("PENGECEKAN KETERSEDIAAN BAHAN PUSTAKA\nDAN CETAK SURAT PEMESANAN BAHAN PUSTAKA");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulUsulanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJudulUsulanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariUsulanActionPerformed(null);
    }//GEN-LAST:event_txtJudulUsulanKeyPressed

    private void btnCariUsulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariUsulanActionPerformed
        // TODO add your handling code here:
        tableUsulan.setModel(C.getUsulanSearch(txtJudulUsulan.getText().trim()));
    }//GEN-LAST:event_btnCariUsulanActionPerformed

    private void btnCariUsulanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariUsulanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariUsulanActionPerformed(null);
    }//GEN-LAST:event_btnCariUsulanKeyPressed

    private void txtJudulBahanPustakaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJudulBahanPustakaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariBahanPustakaActionPerformed(null);
    }//GEN-LAST:event_txtJudulBahanPustakaKeyPressed

    private void btnCariBahanPustakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBahanPustakaActionPerformed
        // TODO add your handling code here:
        tableBahanPustaka.setModel(C.getBahanPustakaSearch(
                txtJudulBahanPustaka.getText().trim()));
    }//GEN-LAST:event_btnCariBahanPustakaActionPerformed

    private void btnCariBahanPustakaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariBahanPustakaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariBahanPustakaActionPerformed(null);
    }//GEN-LAST:event_btnCariBahanPustakaKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tableUsulan.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Data Dari "
                    + "Table Usulan Terlebih Dahulu");
        else
        {
            int pil = JOptionPane.showConfirmDialog(rootPane, 
                    "Hapus Usulan Terpilih ?", "Konfirmasi Penghapusan", 
                    JOptionPane.YES_NO_OPTION);
            
            if(pil == 0)
            {
                C.deleteUsulanCekTersedia(Integer.parseInt(tableUsulan.getValueAt(
                        tableUsulan.getSelectedRow(), 0).toString()));

                setTableDataUsulanVerified();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnHapusActionPerformed(null);
    }//GEN-LAST:event_btnHapusKeyPressed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        String NamaFile = "/View/PesanBukuReport.jasper";
        Connection CON;
        String url = "jdbc:sqlserver://localhost:1433;databaseName=ILUSI_7320;"
                + "user=pp7320;password=7320";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            CON=DriverManager.getConnection(url);
            System.out.println("Success!\n");      
            InputStream report = getClass().getResourceAsStream(NamaFile);
            JasperPrint jprint = JasperFillManager.fillReport(report, null, CON);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {System.out.println(e.toString());}
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnCetakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCetakKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCetakActionPerformed(null);
    }//GEN-LAST:event_btnCetakKeyPressed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelesaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSelesaiActionPerformed(null);
    }//GEN-LAST:event_btnSelesaiKeyPressed

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Color.red);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnCetakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetakMouseEntered
        // TODO add your handling code here:
        btnCetak.setBackground(Color.green);
    }//GEN-LAST:event_btnCetakMouseEntered

    private void btnCetakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetakMouseExited
        // TODO add your handling code here:
        btnCetak.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnCetakMouseExited

    private void btnSelesaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseEntered
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.cyan);
    }//GEN-LAST:event_btnSelesaiMouseEntered

    private void btnSelesaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseExited
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSelesaiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananBahanPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananBahanPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananBahanPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananBahanPustaka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananBahanPustaka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBahanPustaka;
    private javax.swing.JButton btnCariUsulan;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBahanPustaka;
    private javax.swing.JTable tableUsulan;
    private javax.swing.JTextField txtJudulBahanPustaka;
    private javax.swing.JTextField txtJudulUsulan;
    // End of variables declaration//GEN-END:variables
}
