/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.*;
import Model.Pemustaka;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;
import java.awt.Color;

/**
 *
 * @author Well's-Comp
 */
public class PemustakaUI extends javax.swing.JFrame {    
    private PemustakaCtrl C;
    private Pemustaka P;
    private PemustakaPopUI instance;
    /**
     * Creates new form PemustakaUI
     */
    public PemustakaUI() {
        initComponents();
        
        C = new PemustakaCtrl();
        instance = null;
        radioBtnGroup = new ButtonGroup();
        
        clear();
        
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /////////////////////METHOD-METHOD////////////////////////
    private void clear()
    {
        radioBtnGroup.clearSelection();
        txtCari.setText("");
        tableShow.clearSelection();
        
        setTableData();
    }
    
    private void setForm()
    {        
        radioBtnGroup.add(radioBtnNoAnggota);
        radioBtnGroup.add(radioBtnNamaAnggota);
        
        this.setTitle("PENGELOLAAN KATAGORI PEMUSTAKA");
        
        setTable();
    }
    
    private void setTable()
    {
        for(int i = 0; i < tableShow.getColumnCount(); i++)
        {
            Class<?> column = tableShow.getColumnClass(i);
            tableShow.setDefaultEditor(column, null);
        }
        
        tableShow.getTableHeader().setReorderingAllowed(false);
        
        tableShow.setRowSelectionAllowed(false);
        tableShow.setColumnSelectionAllowed(false);
        tableShow.setCellSelectionEnabled(true);
        
        tableShow.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableShow.setDragEnabled(false);
        tableShow.setShowGrid(true);
        
        tableShow.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setTableData()
    {
        tableShow.setModel(C.showPemustaka());
    }
    
    public int getTableSelectedRow()
    {
        return tableShow.getSelectedRow() + 1;
    }
    
    public void setInstance()
    {
        this.instance = null;
    }
    //////////////////////////////////////////////////////////
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        radioBtnNoAnggota = new javax.swing.JRadioButton();
        radioBtnNamaAnggota = new javax.swing.JRadioButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShow = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAktivasi = new javax.swing.JButton();
        btnPerpanjangan = new javax.swing.JButton();
        btnDeaktivasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PENCARIAN");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        radioBtnNoAnggota.setText("No Anggota");

        radioBtnNamaAnggota.setText("Nama Pemustaka");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });

        tableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableShow);

        btnTambah.setText("TAMBAH");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKeyPressed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        btnUbah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUbahKeyPressed(evt);
            }
        });

        btnHapus.setText("TERMINASI");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        btnClear.setText("BERSIHKAN");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClearKeyPressed(evt);
            }
        });

        jLabel2.setText("BERDASARKAN");

        btnAktivasi.setText("AKTIVASI");
        btnAktivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAktivasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAktivasiMouseExited(evt);
            }
        });
        btnAktivasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktivasiActionPerformed(evt);
            }
        });
        btnAktivasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAktivasiKeyPressed(evt);
            }
        });

        btnPerpanjangan.setText("PERPANJANGAN");
        btnPerpanjangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerpanjanganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerpanjanganMouseExited(evt);
            }
        });
        btnPerpanjangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerpanjanganActionPerformed(evt);
            }
        });
        btnPerpanjangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPerpanjanganKeyPressed(evt);
            }
        });

        btnDeaktivasi.setText("DEAKTIVASI");
        btnDeaktivasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeaktivasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeaktivasiMouseExited(evt);
            }
        });
        btnDeaktivasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeaktivasiActionPerformed(evt);
            }
        });
        btnDeaktivasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeaktivasiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioBtnNoAnggota)
                                .addGap(18, 18, 18)
                                .addComponent(radioBtnNamaAnggota))
                            .addComponent(txtCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18)
                .addComponent(btnAktivasi)
                .addGap(18, 18, 18)
                .addComponent(btnPerpanjangan)
                .addGap(18, 18, 18)
                .addComponent(btnDeaktivasi)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAktivasi, btnClear, btnDeaktivasi, btnHapus, btnPerpanjangan, btnTambah, btnUbah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBtnNoAnggota)
                    .addComponent(radioBtnNamaAnggota)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnClear)
                    .addComponent(btnAktivasi)
                    .addComponent(btnPerpanjangan)
                    .addComponent(btnDeaktivasi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String mode = "", cari = txtCari.getText().toString().trim().toLowerCase();
        
        if(radioBtnGroup.getSelection() == null)
            JOptionPane.showMessageDialog(rootPane, 
                    "Silakan Pilih Salah Satu Kategori Pencarian Terlebih Dahulu");
        else if(cari.equalsIgnoreCase("") && radioBtnNoAnggota.isSelected())
            JOptionPane.showMessageDialog(rootPane, 
                    "Silakan Inputkan Data Yang Ingin Dicari Terlebih Dahulu");
        else if(radioBtnNamaAnggota.isSelected())
        {
            mode = "nama_pemustaka";
            tableShow.setModel(C.showCariPemustaka(mode, cari));
        }
        else if(radioBtnNoAnggota.isSelected())
        {
            mode = "no_anggota";
            tableShow.setModel(C.showCariPemustaka(mode, cari));
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariActionPerformed(null);
    }//GEN-LAST:event_btnCariKeyPressed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            (instance = new PemustakaPopUI("add", this, null)).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Maaf, Editor Hanya Bisa Satu Dalam Satu Waktu");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnTambahActionPerformed(null);
    }//GEN-LAST:event_btnTambahKeyPressed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(getTableSelectedRow() != 0)
        {
            if(instance == null)
            {
                (instance = new PemustakaPopUI("edit", this, 
                        C.getRowDataPemustaka(Integer.parseInt(tableShow.getValueAt(
                                tableShow.getSelectedRow(), 0).toString())))).setVisible(true); 
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Maaf, Editor Hanya Bisa Satu Dalam Satu Waktu");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Silakan Pilih Data Pada Tabel Yang Ada");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnUbahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUbahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnUbahActionPerformed(null);
    }//GEN-LAST:event_btnUbahKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(getTableSelectedRow() != 0)
            {
                int pil = JOptionPane.showConfirmDialog(rootPane, "Apakah Yakin Akan Menghapus Data", 
                        "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

                if(pil == 0)
                {
                    C.deletePemustaka(Integer.parseInt(tableShow.getValueAt(
                            tableShow.getSelectedRow(), 0).toString()));
                    setTableData();
                }
            }
            else
                JOptionPane.showMessageDialog(rootPane, 
                        "Silakan Pilih Data Pada Tabel Yang Ada");
        }
        else
            JOptionPane.showMessageDialog(rootPane, 
                    "Sedang Ada Jendela Ubah/Tambah Yang Aktif, Silkan Matikan Dulu");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnHapusActionPerformed(null);
    }//GEN-LAST:event_btnHapusKeyPressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            clear();
    }//GEN-LAST:event_btnClearKeyPressed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariActionPerformed(null);
    }//GEN-LAST:event_txtCariKeyPressed

    private void btnAktivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktivasiActionPerformed
        // TODO add your handling code here:
        if(! tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Mahasiswa UJDP"))
            JOptionPane.showMessageDialog(rootPane, "Aktivasi Hanya Untuk Mahasiswa UJDP");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Dosen UJDP"))
            JOptionPane.showMessageDialog(rootPane, "Aktivasi Tidak Berlaku Untuk Dosen UJDP");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Aktif"))
            JOptionPane.showMessageDialog(rootPane, "Pemustaka Sudah Berstatus Aktif");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Tidak Aktif"))
        {
            C.setStatusAktif(Integer.parseInt(tableShow.getValueAt(
                    tableShow.getSelectedRow(), 0).toString()));
            
            JOptionPane.showMessageDialog(rootPane, "Pemustaka Berhasil Diaktifkan");
            
            setTableData();
        }
    }//GEN-LAST:event_btnAktivasiActionPerformed

    private void btnAktivasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAktivasiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnAktivasiActionPerformed(null);
    }//GEN-LAST:event_btnAktivasiKeyPressed

    private void btnPerpanjanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerpanjanganActionPerformed
        // TODO add your handling code here:
        if(tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Mahasiswa UJDP")
           || tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Dosen UJDP"))
            JOptionPane.showMessageDialog(rootPane, "Perpanjangan Hanya Untuk Mahasiswa dan Dosen Luar");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Dosen UJDP"))
            JOptionPane.showMessageDialog(rootPane, "Perpanjangan Tidak Berlaku Untuk Dosen UJDP");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Aktif"))
            JOptionPane.showMessageDialog(rootPane, "Pemustaka Sudah Berstatus Aktif");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Tidak Aktif"))
        {
            C.setStatusAktif(Integer.parseInt(tableShow.getValueAt(
                    tableShow.getSelectedRow(), 0).toString()));
            
            JOptionPane.showMessageDialog(rootPane, "Pemustaka Berhasil Diaktifkan");
            
            setTableData();
        }
    }//GEN-LAST:event_btnPerpanjanganActionPerformed

    private void btnPerpanjanganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPerpanjanganKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnPerpanjanganActionPerformed(null);
    }//GEN-LAST:event_btnPerpanjanganKeyPressed

    private void btnDeaktivasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeaktivasiActionPerformed
        // TODO add your handling code here:
        if(tableShow.getValueAt(tableShow.getSelectedRow(), 9).toString().equalsIgnoreCase("Dosen UJDP"))
            JOptionPane.showMessageDialog(rootPane, "Deaktivasi Tidak Berlaku Untuk Dosen UJDP");
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Aktif"))
        {
            SimpleDateFormat df = new SimpleDateFormat("dd/MM");
            Calendar tgl = Calendar.getInstance();
            String tglSkrg = df.format(tgl.getTime());
            
            if(tglSkrg.equalsIgnoreCase("31/12") || tglSkrg.equalsIgnoreCase("31/07"))
            {
                C.setDeaktivasi(Integer.parseInt(tableShow.getValueAt(
                        tableShow.getSelectedRow(), 0).toString()));

                JOptionPane.showMessageDialog(rootPane, "Pemustaka Berhasil Dideaktivasi");


                setTableData();
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Belum Tanggal 31 Desember atau 31 Juli");
        }
        else if(tableShow.getValueAt(tableShow.getSelectedRow(), 10).toString().equalsIgnoreCase("Tidak Aktif"))
            JOptionPane.showMessageDialog(rootPane, "Status Pemustaka Sudah Tidak Aktif");
    }//GEN-LAST:event_btnDeaktivasiActionPerformed

    private void btnDeaktivasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeaktivasiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnDeaktivasiActionPerformed(null);
    }//GEN-LAST:event_btnDeaktivasiKeyPressed

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        btnTambah.setBackground(Color.green);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        btnTambah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseEntered
        // TODO add your handling code here:
        btnUbah.setBackground(Color.green);
    }//GEN-LAST:event_btnUbahMouseEntered

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        // TODO add your handling code here:
        btnUbah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Color.red);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(Color.yellow);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        btnClear.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnDeaktivasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeaktivasiMouseEntered
        // TODO add your handling code here:
        btnDeaktivasi.setBackground(Color.red);
    }//GEN-LAST:event_btnDeaktivasiMouseEntered

    private void btnDeaktivasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeaktivasiMouseExited
        // TODO add your handling code here:
        btnDeaktivasi.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnDeaktivasiMouseExited

    private void btnAktivasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAktivasiMouseEntered
        // TODO add your handling code here:
        btnAktivasi.setBackground(Color.green);
    }//GEN-LAST:event_btnAktivasiMouseEntered

    private void btnAktivasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAktivasiMouseExited
        // TODO add your handling code here:
        btnAktivasi.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnAktivasiMouseExited

    private void btnPerpanjanganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerpanjanganMouseEntered
        // TODO add your handling code here:
        btnPerpanjangan.setBackground(Color.green);
    }//GEN-LAST:event_btnPerpanjanganMouseEntered

    private void btnPerpanjanganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerpanjanganMouseExited
        // TODO add your handling code here:
        btnPerpanjangan.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnPerpanjanganMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemustakaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktivasi;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeaktivasi;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPerpanjangan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JRadioButton radioBtnNamaAnggota;
    private javax.swing.JRadioButton radioBtnNoAnggota;
    private javax.swing.JTable tableShow;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
