/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.PeminjamanCtrl;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.*;
import java.awt.Color;

/**
 *
 * @author Well's-Comp
 */
public class PengelolaanPeminjamanUI extends javax.swing.JFrame {
    private PeminjamanCtrl C;
    private PengelolaanPeminjamanPopUI instance;
    private DefaultTableModel tableModel;
    /**
     * Creates new form PengelolaanPeminjaman
     */
    public PengelolaanPeminjamanUI() {
        initComponents();
        
        C = new PeminjamanCtrl();
        tableModel = new DefaultTableModel(null, C.columnNames());
        instance = null;
        
        clear();
        setForm();
    }

    ///////////////////////////////METHOD-METHOD////////////////////////////////
    private void setForm()
    {
        btnHapus.setEnabled(false);
        btnTambah.setEnabled(false);
        btnSimpan.setEnabled(false);
        
        this.setTitle("PENGELOLAAN PEMINJAMAN BAHAN PUSTAKA");
        
        setTable();
    }
    
    private void clear()
    {
        tableData.clearSelection();
    }
    
    private void setTable()
    {
        for(int i = 0; i < tableData.getColumnCount(); i++)
        {
            Class<?> column = tableData.getColumnClass(i);
            tableData.setDefaultEditor(column, null);
        }
        
        tableData.getTableHeader().setReorderingAllowed(false);
        
        tableData.setRowSelectionAllowed(false);
        tableData.setColumnSelectionAllowed(false);
        tableData.setCellSelectionEnabled(true);
        
        tableData.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableData.setDragEnabled(false);
        tableData.setShowGrid(true);
        
        tableData.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tableData.setModel(tableModel);
    }
    
    public int getTableSelectedRow()
    {
        return tableData.getSelectedRow();
    }
    
    public void setInstance()
    {
        this.instance = null;
    }
    
    private void setInputPeminjamanOn()
    {
        btnHapus.setEnabled(true);
        btnTambah.setEnabled(true);
        btnSimpan.setEnabled(true);
    }
    
    private void setTanggalPinjamKembali()
    {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        
        /////tanggal pinjam/////
        Calendar tgl = Calendar.getInstance();
        ////////////////////////
        
        labelTanggalPinjam.setText(df.format(tgl.getTime()));
        
        //////penambahan tanggal untuk pengembalian/////
        int hari = C.getLamaPinjamPemustaka(Integer.valueOf(
                txtNoAnggota.getText().trim()));
        
        tgl.add(Calendar.DATE, hari);
        ////////////////////////////////////////////////
        
        labelTanggalKembali.setText(df.format(tgl.getTime()));
    }
    
    public void addDataTableModel(String noKatalog, String noISBN, String judul, 
            String penerbit, String pengarang)
    {
        tableModel.addRow(new Object[]{noKatalog, noISBN, judul, penerbit, 
            pengarang});
    }
    ///////////////////////////////METHOD-METHOD////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNoAnggota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnCekNoAnggota = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        labelTanggalPinjam = new javax.swing.JLabel();
        labelTanggalKembali = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoAnggotaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoAnggotaKeyTyped(evt);
            }
        });

        jLabel1.setText("No. ANGGOTA");

        jLabel3.setText("TANGGAL PENGEMBALIAN");

        jLabel2.setText("TANGGAL PEMINJAMAN");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        btnCekNoAnggota.setText("CEK NO. ANGGOTA");
        btnCekNoAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCekNoAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCekNoAnggotaMouseExited(evt);
            }
        });
        btnCekNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekNoAnggotaActionPerformed(evt);
            }
        });
        btnCekNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCekNoAnggotaKeyPressed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKeyPressed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        labelTanggalPinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggalPinjam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTanggalKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggalKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(labelTanggalPinjam))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(labelTanggalKembali))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnCekNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelTanggalKembali, labelTanggalPinjam, txtNoAnggota});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnSimpan, btnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekNoAnggota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelTanggalPinjam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelTanggalKembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelTanggalKembali, labelTanggalPinjam, txtNoAnggota});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaActionPerformed
        // TODO add your handling code here:
        Pattern ptrn = Pattern.compile("[0-9]+");
        
        if(txtNoAnggota.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(rootPane, "Silakan Masukkan No. Anggota");
        else if(! ptrn.matcher(txtNoAnggota.getText().trim()).matches())
            JOptionPane.showMessageDialog(rootPane, "No. Anggota Hanya Angka");
        else
        {
            if(C.cekPemustaka(Integer.valueOf(txtNoAnggota.getText().trim())).
                    equalsIgnoreCase("Aktif"))
            {
                JOptionPane.showMessageDialog(rootPane, "No. Anggota Terdaftar."
                        + "\nSilakan Masukkan Bahan Pustaka Yang Dipinjam");
                
                setInputPeminjamanOn();
                setTanggalPinjamKembali();
                
                btnCekNoAnggota.setEnabled(false);
                
                txtNoAnggota.setEditable(false);
            }
            else if(C.cekPemustaka(Integer.valueOf(txtNoAnggota.getText().trim())).
                    equalsIgnoreCase("Tidak Aktif"))
                JOptionPane.showMessageDialog(rootPane, "Pemustaka Berstatus Tidak Aktif."
                        + " \nTidak Dapat Melakukan Peminjaman");
            else
                JOptionPane.showMessageDialog(rootPane, "No. Anggota Tidak Ditemukan."
                        + " \nSilakan Masukkan Ulang No. Anggota");
        }
    }//GEN-LAST:event_btnCekNoAnggotaActionPerformed

    private void btnCekNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCekNoAnggotaActionPerformed(null);
    }//GEN-LAST:event_btnCekNoAnggotaKeyPressed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(C.getJumlahPinjaman(Integer.parseInt(txtNoAnggota.getText().trim())) >= 15)
                JOptionPane.showMessageDialog(rootPane, "Jumlah Bahan Pustaka Dipinjam Sudah 15 atau Lebih.\n"
                        + "Pemustaka Tidak Dapat Melakukan Peminjaman Lagi");
            else
            {
                instance = new PengelolaanPeminjamanPopUI(this);
                instance.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Sudah Ada Jendela Tambah Yang Aktif");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnTambahActionPerformed(null);
    }//GEN-LAST:event_btnTambahKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(tableData.getSelectedRow() != -1)
            {
                int pil = JOptionPane.showConfirmDialog(rootPane, 
                        "Hapus Bahan Pustaka ?", "Konfirmasi Penghapusan", 
                        JOptionPane.YES_NO_OPTION);

                if(pil == 0)
                {
                    C.KembaliBahanPustaka(tableData.getValueAt(
                            tableData.getSelectedRow(), 0).toString());

                    tableModel.removeRow(tableData.getSelectedRow());
                }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Data Yang Ingin Dihapus");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Masih Ada Jendela Tambah Yang Aktif");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnHapusActionPerformed(null);
    }//GEN-LAST:event_btnHapusKeyPressed

    private void txtNoAnggotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAnggotaKeyTyped
        // TODO add your handling code here:
        if(! Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtNoAnggotaKeyTyped

    private void txtNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAnggotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCekNoAnggotaActionPerformed(null);
    }//GEN-LAST:event_txtNoAnggotaKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(tableData.getRowCount() != 0)
            {
                int pil = JOptionPane.showConfirmDialog(rootPane, 
                        "Simpan Daftar Bahan Pustaka Yang Dipinjam ?", 
                        "Konfirmasi Penyimpanan", JOptionPane.YES_NO_OPTION);

                if(pil == 0)
                {
                    int id_transaksi = C.getNewIDTransaksi();

                    C.insertNewTransaksi(id_transaksi, Integer.valueOf(
                            txtNoAnggota.getText().trim()), labelTanggalPinjam.getText(), 
                            labelTanggalKembali.getText());

                    for(int i = 0; i < tableModel.getRowCount(); i++)
                    {
                        C.insertNewDetilTransaksi(id_transaksi, 
                                tableModel.getValueAt(i, 0).toString());
                    }

                    JOptionPane.showMessageDialog(rootPane, 
                            "Data Peminjaman Berhasil Dimasukkan");

                    this.dispose();
                }
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Silahkan Masukkan Bahan "
                        + "Pustaka Yang Ingin Dipinjam Terlebih Dahulu");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Masih Ada Jendela Tambah Yang Aktif");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSimpanActionPerformed(null);
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        // TODO add your handling code here:
        btnSimpan.setBackground(Color.cyan);
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        // TODO add your handling code here:
        btnSimpan.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        btnTambah.setBackground(Color.green);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        btnTambah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Color.red);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnCekNoAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaMouseEntered
        // TODO add your handling code here:
        btnCekNoAnggota.setBackground(Color.green);
    }//GEN-LAST:event_btnCekNoAnggotaMouseEntered

    private void btnCekNoAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaMouseExited
        // TODO add your handling code here:
        btnCekNoAnggota.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnCekNoAnggotaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPeminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPeminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPeminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPeminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengelolaanPeminjamanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekNoAnggota;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTanggalKembali;
    private javax.swing.JLabel labelTanggalPinjam;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtNoAnggota;
    // End of variables declaration//GEN-END:variables
}
