/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.PengelolaanBahanPustakaAutoCtrl;
import Control.PengelolaanBahanPustakaCtrl;
import Model.BahanPustaka;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import java.awt.Color;

/**
 *
 * @author Well's-Comp
 */
public class PengelolaanBahanPustakaAutoUI extends javax.swing.JFrame {
    private PengelolaanBahanPustakaAutoCtrl C;
    private static PengelolaanBahanPustakaPopUI instance;
    /**
     * Creates new form PengelolaanBahanPustakaAutoUI
     */
    public PengelolaanBahanPustakaAutoUI() {
        initComponents();
        
        C = new PengelolaanBahanPustakaAutoCtrl();
        instance = null;
        
        clear();
        setForm();
    }

    ///////////////////////////////METHOD-METHOD////////////////////////////////
    private void setForm()
    {
        this.setTitle("PENGECEKAN KETERSEDIAAN "
                + "DAN CETAK SURAT PEMESANAN BAHAN PUSTAKA");
        
        setTableDataBhnPustaka();
        setTableDataUsulanVerified();
        
        setTableUsulan();
        setTableBahanPustaka();
    }
    
    private void clear()
    {
        tableUsulan.clearSelection();
        tableBahanPustaka.clearSelection();
        
        
    }
    
    public void setInstance()
    {
        this.instance = null;
    }
    
    private void setTableUsulan()
    {
        for(int i = 0; i < tableUsulan.getColumnCount(); i++)
        {
            Class<?> column = tableUsulan.getColumnClass(i);
            tableUsulan.setDefaultEditor(column, null);
        }
        
        tableUsulan.getTableHeader().setReorderingAllowed(false);
        
        tableUsulan.setRowSelectionAllowed(false);
        tableUsulan.setColumnSelectionAllowed(false);
        tableUsulan.setCellSelectionEnabled(true);
        
        tableUsulan.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableUsulan.setDragEnabled(false);
        tableUsulan.setShowGrid(true);
        
        tableUsulan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void setTableBahanPustaka()
    {
        for(int i = 0; i < tableBahanPustaka.getColumnCount(); i++)
        {
            Class<?> column = tableBahanPustaka.getColumnClass(i);
            tableBahanPustaka.setDefaultEditor(column, null);
        }
        
        //tableBahanPustaka.getColumnModel().getColumn(0).setPreferredWidth(93);
        
        tableBahanPustaka.getTableHeader().setReorderingAllowed(false);
        
        tableBahanPustaka.setRowSelectionAllowed(false);
        tableBahanPustaka.setColumnSelectionAllowed(false);
        tableBahanPustaka.setCellSelectionEnabled(true);
        
        tableBahanPustaka.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableBahanPustaka.setDragEnabled(false);
        tableBahanPustaka.setShowGrid(true);
        
        tableBahanPustaka.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    public void setTableDataBhnPustaka()
    {
        tableBahanPustaka.setModel(C.getTableDataBahanPustaka());
    }
    
    private void setTableDataUsulanVerified()
    {
        tableUsulan.setModel(C.getTableDataUsulan());
    }
    ///////////////////////////////METHOD-METHOD////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtJudulUsulan = new javax.swing.JTextField();
        btnCariUsulan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsulan = new javax.swing.JTable();
        btnSelesai = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtJudulBahanPustaka = new javax.swing.JTextField();
        btnCariBahanPustaka = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBahanPustaka = new javax.swing.JTable();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DATA USULAN BAHAN PUSTAKA TERVERIFIKASI");

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("JUDUL BUKU");

        txtJudulUsulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJudulUsulanKeyPressed(evt);
            }
        });

        btnCariUsulan.setText("CARI");
        btnCariUsulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariUsulanActionPerformed(evt);
            }
        });
        btnCariUsulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariUsulanKeyPressed(evt);
            }
        });

        tableUsulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUsulan);

        btnSelesai.setText("SELESAI");
        btnSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseExited(evt);
            }
        });
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        btnSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelesaiKeyPressed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJudulUsulan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariUsulan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSelesai, btnTambah});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudulUsulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariUsulan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnTambah))
                .addGap(3, 3, 3))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 447));

        jLabel4.setText("JUDUL BUKU");

        txtJudulBahanPustaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJudulBahanPustakaKeyPressed(evt);
            }
        });

        btnCariBahanPustaka.setText("CARI");
        btnCariBahanPustaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBahanPustakaActionPerformed(evt);
            }
        });
        btnCariBahanPustaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariBahanPustakaKeyPressed(evt);
            }
        });

        tableBahanPustaka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableBahanPustaka);

        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        btnUbah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUbahKeyPressed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJudulBahanPustaka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariBahanPustaka, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnUbah});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJudulBahanPustaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBahanPustaka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(3, 3, 3))
        );

        jLabel2.setText("DATA BAHAN PUSTAKA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulUsulanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJudulUsulanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariUsulanActionPerformed(null);
    }//GEN-LAST:event_txtJudulUsulanKeyPressed

    private void btnCariUsulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariUsulanActionPerformed
        // TODO add your handling code here:
        tableUsulan.setModel(C.getUsulanSearch(txtJudulUsulan.getText().trim()));
    }//GEN-LAST:event_btnCariUsulanActionPerformed

    private void btnCariUsulanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariUsulanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariUsulanActionPerformed(null);
    }//GEN-LAST:event_btnCariUsulanKeyPressed

    private void txtJudulBahanPustakaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJudulBahanPustakaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariBahanPustakaActionPerformed(null);
    }//GEN-LAST:event_txtJudulBahanPustakaKeyPressed

    private void btnCariBahanPustakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBahanPustakaActionPerformed
        // TODO add your handling code here:
        tableBahanPustaka.setModel(C.getBahanPustakaSearch(
                txtJudulBahanPustaka.getText().trim()));
    }//GEN-LAST:event_btnCariBahanPustakaActionPerformed

    private void btnCariBahanPustakaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariBahanPustakaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnCariBahanPustakaActionPerformed(null);
    }//GEN-LAST:event_btnCariBahanPustakaKeyPressed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(tableUsulan.getSelectedRow() == -1)
            JOptionPane.showMessageDialog(rootPane, 
                    "Silahkan Pilih Data Yang Ingin Dimasukkan Dari Tabel Usulan");
        else
        {
            DateFormat df = new SimpleDateFormat("yyyy");
            
            Vector data = C.getRowDataUsulan(Integer.parseInt(
                    tableUsulan.getValueAt(tableUsulan.getSelectedRow(), 0).toString()));
            
            for(int i=0; i < Integer.parseInt(data.get(4).toString()); i++)
            {
                C.insertBahanPustaka(new BahanPustaka(data.get(5).toString()
                    + "." + df.format(Calendar.getInstance().getTime()) + "-" 
                    + C.getMaxKodeKatalog(), data.get(0).toString(), 
                    data.get(1).toString(), data.get(2).toString(), data.get(3).toString(),                     
                    Integer.parseInt(data.get(5).toString())));
            }
            
            C.deleteUsulan(Integer.parseInt(
                    tableUsulan.getValueAt(tableUsulan.getSelectedRow(), 0).toString()));
            
            JOptionPane.showMessageDialog(rootPane, "Bahan Pustaka Berhasil Dimasukkan");
            
            setTableDataUsulanVerified();
            setTableDataBhnPustaka();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnTambahActionPerformed(null);
    }//GEN-LAST:event_btnTambahKeyPressed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelesaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSelesaiActionPerformed(null);
    }//GEN-LAST:event_btnSelesaiKeyPressed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(tableBahanPustaka.getSelectedRow() != -1)
        {
            if(instance == null)
            {
                (instance = new PengelolaanBahanPustakaPopUI(this, "edit", 
                        C.getRowDataBahanPustaka(tableBahanPustaka.getValueAt(
                                tableBahanPustaka.getSelectedRow(), 0).toString()))).setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Masih Ada Jendela Ubah Yang Aktif");
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Bahan Pustaka Yang Ingin Diubah");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnUbahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUbahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnUbahActionPerformed(null);
    }//GEN-LAST:event_btnUbahKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(tableBahanPustaka.getSelectedRow() != -1)
            {
                int pil = JOptionPane.showConfirmDialog(rootPane, 
                        "Apakah Anda Yakin Akan Menghapus Bahan Pustaka Ini?", 
                        "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE);

                if(pil == 0)
                {
                    C.deleteBahanPustaka(tableBahanPustaka.getValueAt(
                            tableBahanPustaka.getSelectedRow(), 0).toString());
                    
                    setTableDataBhnPustaka();
                }
            }
            else
                JOptionPane.showMessageDialog(rootPane, 
                        "Silakan Pilih Data Pada Tabel Yang Ada");
        }
        else
            JOptionPane.showMessageDialog(rootPane, 
                    "Sedang Ada Jendela Ubah/Tambah Yang Aktif, Silkan Matikan Dulu");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnHapusActionPerformed(null);
    }//GEN-LAST:event_btnHapusKeyPressed

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        btnTambah.setBackground(Color.green);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        btnTambah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseEntered
        // TODO add your handling code here:
        btnUbah.setBackground(Color.green);
    }//GEN-LAST:event_btnUbahMouseEntered

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        // TODO add your handling code here:
        btnUbah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Color.red);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnSelesaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseEntered
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.cyan);
    }//GEN-LAST:event_btnSelesaiMouseEntered

    private void btnSelesaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseExited
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSelesaiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengelolaanBahanPustakaAutoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengelolaanBahanPustakaAutoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengelolaanBahanPustakaAutoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengelolaanBahanPustakaAutoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengelolaanBahanPustakaAutoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBahanPustaka;
    private javax.swing.JButton btnCariUsulan;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBahanPustaka;
    private javax.swing.JTable tableUsulan;
    private javax.swing.JTextField txtJudulBahanPustaka;
    private javax.swing.JTextField txtJudulUsulan;
    // End of variables declaration//GEN-END:variables
}
