/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.PengembalianCtrl;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Well's-Comp
 */
public class PengelolaanPengembalianUI extends javax.swing.JFrame {
    private PengembalianCtrl C;
    private int total_denda;
    private ArrayList<String> no_detil;
    /**
     * Creates new form PengelolaanPengembalianUI
     */
    public PengelolaanPengembalianUI() {
        initComponents();
        
        C = new PengembalianCtrl();
        total_denda = 0;
        no_detil = new ArrayList<String>();
        
        clear();
        setForm();
    }

    ///////////////////////////////METHOD-METHOD////////////////////////////////
    private void setForm()
    {
        btnPengembalian.setEnabled(false);
        
        labelDenda.setText("Rp. " + total_denda);
        
        this.setTitle("PENGELOLAAN PENGEMBALIAN BAHAN PUSTAKA");
        
        setTable();
    }
    
    private void clear()
    {
        tableData.clearSelection();
    }
    
    private void setTable()
    {
        for(int i = 0; i < tableData.getColumnCount(); i++)
        {
            Class<?> column = tableData.getColumnClass(i);
            tableData.setDefaultEditor(column, null);
        }
        
        tableData.getTableHeader().setReorderingAllowed(false);
        
        tableData.setRowSelectionAllowed(false);
        tableData.setColumnSelectionAllowed(false);
        tableData.setCellSelectionEnabled(true);
        
        tableData.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableData.setDragEnabled(false);
        tableData.setShowGrid(true);
        
        tableData.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tableData.setModel(new DefaultTableModel(null, C.columnNames()));
    }
    
    public int getTableSelectedRow()
    {
        return tableData.getSelectedRow();
    }
    
    private void setInputPengembalianOn()
    {
        btnPengembalian.setEnabled(true);
        btnSelesai.setEnabled(true);
    }
    
    private void setTanggalKembali()
    {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");

        Calendar tgl = Calendar.getInstance();
        
        labelTanggalKembaliAktual.setText(df.format(tgl.getTime()));
    }
    ///////////////////////////////METHOD-METHOD////////////////////////////////

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNoAnggota = new javax.swing.JTextField();
        labelTanggalKembaliAktual = new javax.swing.JLabel();
        btnCekNoAnggota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        btnPengembalian = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelDenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setText("No. ANGGOTA");

        jLabel5.setText("TANGGAL KEMBALI");

        txtNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoAnggotaKeyPressed(evt);
            }
        });

        labelTanggalKembaliAktual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggalKembaliAktual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCekNoAnggota.setText("CEK NO. ANGGOTA");
        btnCekNoAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCekNoAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCekNoAnggotaMouseExited(evt);
            }
        });
        btnCekNoAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekNoAnggotaActionPerformed(evt);
            }
        });
        btnCekNoAnggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCekNoAnggotaKeyPressed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableData);

        btnPengembalian.setText("PENGEMBALIAN");
        btnPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPengembalianMouseExited(evt);
            }
        });
        btnPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianActionPerformed(evt);
            }
        });
        btnPengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPengembalianKeyPressed(evt);
            }
        });

        btnSelesai.setText("SELESAI");
        btnSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSelesaiMouseExited(evt);
            }
        });
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });
        btnSelesai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSelesaiKeyPressed(evt);
            }
        });

        jLabel1.setText("TOTAL DENDA :");

        labelDenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDenda.setText("jLabel2");
        labelDenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelDenda.setPreferredSize(new java.awt.Dimension(40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCekNoAnggota))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelTanggalKembaliAktual)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPengembalian)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelTanggalKembaliAktual, txtNoAnggota});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPengembalian, btnSelesai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekNoAnggota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelTanggalKembaliAktual))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPengembalian)
                        .addComponent(btnSelesai)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelTanggalKembaliAktual, txtNoAnggota});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAnggotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        btnCekNoAnggotaActionPerformed(null);
    }//GEN-LAST:event_txtNoAnggotaKeyPressed

    private void btnCekNoAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaActionPerformed
        // TODO add your handling code here:
        Pattern ptrn = Pattern.compile("[0-9]+");

        if(txtNoAnggota.getText().equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(rootPane, "Silakan Masukkan No. Anggota");
        else if(! ptrn.matcher(txtNoAnggota.getText().trim()).matches())
            JOptionPane.showMessageDialog(rootPane, "No. Anggota Hanya Angka");
        else
        {
            if(C.cekPemustaka(Integer.valueOf(txtNoAnggota.getText().trim())).
                    equalsIgnoreCase("Tidak Aktif") || 
               C.cekPemustaka(Integer.valueOf(txtNoAnggota.getText().trim())).
                       equalsIgnoreCase("Aktif"))
            {
                JOptionPane.showMessageDialog(rootPane, "No. Anggota Terdaftar."
                    + "\nSilahkan Memproses Pengembalian Bahan Pustaka");

                setInputPengembalianOn();
                setTanggalKembali();

                btnCekNoAnggota.setEnabled(false);

                txtNoAnggota.setEditable(false);

                tableData.setModel(C.getDataPeminjaman(Integer.valueOf(
                    txtNoAnggota.getText().trim())));
            }
            else
            JOptionPane.showMessageDialog(rootPane, "No. Anggota Tidak Ditemukan."
                + " \nSilakan Masukkan Ulang No. Anggota");
        }
    }//GEN-LAST:event_btnCekNoAnggotaActionPerformed

    private void btnCekNoAnggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        btnCekNoAnggotaActionPerformed(null);
    }//GEN-LAST:event_btnCekNoAnggotaKeyPressed

    private void btnPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianActionPerformed
        // TODO add your handling code here:
        if(tableData.getSelectedRow() != -1)
        {
            int pil = JOptionPane.showConfirmDialog(rootPane,
                "Konfirmasi Pengembalian Bahan Pustaka Ini",
                "Konfirmasi Pengembalian", JOptionPane.YES_NO_OPTION);

            if(pil == 0)
            {
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
                DateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
                Date tglKembali = null, tglKemAktual = null;
                
                try {
                    tglKembali = df2.parse(C.getTanggalKembali(Integer.valueOf(
                            txtNoAnggota.getText().trim()),
                            tableData.getValueAt(tableData.getSelectedRow(), 1).toString()));
                    
                    tglKemAktual = df.parse(labelTanggalKembaliAktual.getText());
                }
                catch (ParseException ex) {
                    Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                no_detil.add(tableData.getValueAt(tableData.getSelectedRow(), 0).toString());
                
                if(tglKemAktual.after(tglKembali))
                {
                    int diff = (int) (tglKemAktual.getTime() - tglKembali.getTime())/
                            (24 * 60 * 60 * 1000);
                    
                    labelDenda.setText("Rp. " + String.valueOf(total_denda += diff * 500));
                    
                    C.KembaliBahanPustaka(tableData.getValueAt(
                        tableData.getSelectedRow(), 1).toString());
                    
                    C.pengembalianBahanPustakaDenda(Integer.valueOf(
                            tableData.getValueAt(tableData.getSelectedRow(), 0).toString()),
                            labelTanggalKembaliAktual.getText(), diff * 500);
                }
                else
                {
                    C.KembaliBahanPustaka(tableData.getValueAt(
                        tableData.getSelectedRow(), 1).toString());
                    
                    C.pengembalianBahanPustaka(Integer.valueOf(
                            tableData.getValueAt(tableData.getSelectedRow(), 0).toString()),
                        labelTanggalKembaliAktual.getText());
                }
                
                JOptionPane.showMessageDialog(rootPane, "Bahan Pustaka Berhasil Dikembalikan");

                tableData.setModel(C.getDataPeminjaman(Integer.valueOf(
                    txtNoAnggota.getText().trim())));
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Bahan Pustaka "
                + "Yang Akan Dikembalikan Dari Tabel");
    }//GEN-LAST:event_btnPengembalianActionPerformed

    private void btnPengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPengembalianKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnPengembalianActionPerformed(null);
    }//GEN-LAST:event_btnPengembalianKeyPressed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        if(btnCekNoAnggota.isEnabled() == false)
        {
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

            if(Integer.parseInt(labelDenda.getText().substring(4)) > 0){
                JOptionPane.showMessageDialog(rootPane, "Terdapat Denda Sebesar : "
                    + labelDenda.getText() + "\nUntuk Keterlambatan Pengembalian "
                    + "Bahan Pustaka");

                    Connection CON;
                    HashMap param = new HashMap();
                    String url = "jdbc:sqlserver://localhost;databaseName=ILUSI_7320;"
                            + "user=pp7320;password=7320;";
                    try {
                        InputStream gambar = getClass().getResourceAsStream("/Images/Untitled-1.jpg");
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        param.put("no_anggota", Integer.parseInt(txtNoAnggota.getText().trim()));
                        param.put("tgl_kembali_aktual", df.parse(labelTanggalKembaliAktual.getText()));
                        param.put("printed", "0");
                        param.put("logo", gambar);
                        CON=DriverManager.getConnection(url);
                        System.out.println("Success!\n");      
                        InputStream report;
                        report = getClass().getResourceAsStream("/View/Denda.jasper");
                        JasperPrint jprint = JasperFillManager.fillReport(report, param,CON);
                        JasperViewer viewer = new JasperViewer(jprint, false);
                        viewer.setZoomRatio(1);
                        viewer.setVisible(true);
                    } catch (Exception e) {System.out.println(e.toString());}
            }

            C.setPrinted(no_detil);
        }
        
        this.dispose();
        
        
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnSelesaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSelesaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSelesaiActionPerformed(null);
    }//GEN-LAST:event_btnSelesaiKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        btnSelesaiActionPerformed(null); 
//        
//        
//        synchronized(evt)
//        {
//            try {
//                wait();
//            } catch (InterruptedException ex) {
//                Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        JOptionPane.showMessageDialog(rootPane, "Silakan Gunakan Tombol Selesai");
//        
//        evt.
        
    }//GEN-LAST:event_formWindowClosing

    private void btnPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseEntered
        // TODO add your handling code here:
        btnPengembalian.setBackground(Color.green);
    }//GEN-LAST:event_btnPengembalianMouseEntered

    private void btnPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengembalianMouseExited
        // TODO add your handling code here:
        btnPengembalian.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnPengembalianMouseExited

    private void btnSelesaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseEntered
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.cyan);
    }//GEN-LAST:event_btnSelesaiMouseEntered

    private void btnSelesaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelesaiMouseExited
        // TODO add your handling code here:
        btnSelesai.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSelesaiMouseExited

    private void btnCekNoAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaMouseEntered
        // TODO add your handling code here:
        btnCekNoAnggota.setBackground(Color.green);
    }//GEN-LAST:event_btnCekNoAnggotaMouseEntered

    private void btnCekNoAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekNoAnggotaMouseExited
        // TODO add your handling code here:
        btnCekNoAnggota.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnCekNoAnggotaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengelolaanPengembalianUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengelolaanPengembalianUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekNoAnggota;
    private javax.swing.JButton btnPengembalian;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDenda;
    private javax.swing.JLabel labelTanggalKembaliAktual;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtNoAnggota;
    // End of variables declaration//GEN-END:variables
}
