/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Control.PengusulanBahanPustakaCtrl;
import com.sun.jmx.snmp.BerDecoder;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.util.calendar.BaseCalendar;
import sun.util.calendar.LocalGregorianCalendar;

/**
 *
 * @author Well's-Comp
 */
public class PengusulanBahanPustakaUI extends javax.swing.JFrame {
    private static PengusulanBahanPustakaCtrl C;
    private static PengusulanBahanPustakaPopUI instance;
    
    private static DefaultTableModel tableModel;
    
    private static String namaAnggota;
    private static String noAnggota;
    private static String katPem;
    private static String prodi;
    
    private static int IdUsulan;
    private static int IdProdi;
    
    /**
     * Creates new form PengusulanBahanPustakaUI
     */
    public PengusulanBahanPustakaUI(String _nama, String _no, String _katPem, 
            String _prodi) {
        initComponents();
        
        this.instance = null;
        this.C = new PengusulanBahanPustakaCtrl();
        
        this.tableModel = new DefaultTableModel();
        
        this.namaAnggota = _nama;
        this.noAnggota = _no;
        this.katPem = _katPem;
        this.prodi = _prodi;
        
        this.IdProdi = C.getIDProdi(_prodi);
        
        clear();
        setTableModel();
        setForm();
    }
    
    /////////////////////METHOD-METHOD////////////////////////
    private void clear()
    {
        tableShow.clearSelection();
    }
    
    private void setForm()
    {   
        txtNama.setText(namaAnggota); txtNama.setEditable(false);
        txtNoAnggota.setText(noAnggota); txtNoAnggota.setEditable(false);
        txtKatPem.setText(katPem); txtKatPem.setEditable(false);
        txtProdi.setText(prodi); txtProdi.setEditable(false);
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        labelTanggal.setText(df.format(Calendar.getInstance().getTime()));
        
        this.setTitle("PENGUSULAN BAHAN PUSTAKA");
        
        setTable();
        
        //reservedUsulan();
    }
    
    private void setTableModel()
    {
        tableModel.addColumn("No. ISBN");
        tableModel.addColumn("Judul Buku");
        tableModel.addColumn("Pengarang Buku");
        tableModel.addColumn("Penerbit Buku");
    }
    
    private void setTable()
    {
        for(int i = 0; i < tableShow.getColumnCount(); i++)
        {
            Class<?> column = tableShow.getColumnClass(i);
            tableShow.setDefaultEditor(column, null);
        }
        
        tableShow.getTableHeader().setReorderingAllowed(false);
        
        tableShow.setRowSelectionAllowed(false);
        tableShow.setColumnSelectionAllowed(false);
        tableShow.setCellSelectionEnabled(true);
        
        tableShow.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        tableShow.setDragEnabled(false);
        tableShow.setShowGrid(true);
        
        tableShow.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tableShow.setModel(tableModel);
    }
    
    public int getTableSelectedRow()
    {
        return tableShow.getSelectedRow();
    }
    
    public void setInstance()
    {
        this.instance = null;
    }
    
    private void reservedUsulan()
    {
        C.reservedUsulan(this.IdUsulan, Integer.parseInt(this.noAnggota), 
                this.labelTanggal.getText());
    }
    
    public void addDataTableModel(String noISBN, String judul, String penerbit,
                                  String pengarang)
    {
        tableModel.addRow(new Object[]{noISBN, judul, 
                                       penerbit, pengarang});
    }
    
    public void editDataTableModel(int row, String noISBN, String judul, 
                                   String penerbit, String pengarang)
    {
        String[] dataTemp = {noISBN, judul, penerbit, pengarang};
        
        for(int i = 0; i < tableModel.getColumnCount(); i++)
            tableModel.setValueAt(dataTemp[i], row, i);
    }
    //////////////////////////////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShow = new javax.swing.JTable();
        txtNama = new javax.swing.JTextField();
        txtNoAnggota = new javax.swing.JTextField();
        txtKatPem = new javax.swing.JTextField();
        txtProdi = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NAMA :");

        jLabel2.setText("No. ANGGOTA");

        jLabel3.setText("STATUS");

        jLabel4.setText("PRODI");

        jLabel5.setText("TANGGAL");

        labelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTanggal.setText("jLabel6");
        labelTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableShow);

        btnTambah.setText("TAMBAH");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        btnTambah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKeyPressed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        btnUbah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUbahKeyPressed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKatPem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTanggal)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelTanggal, txtKatPem, txtNama, txtNoAnggota, txtProdi});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnSimpan, btnTambah, btnUbah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKatPem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(C.statusPemustaka(Integer.parseInt(noAnggota)))
            {
                (instance = new PengusulanBahanPustakaPopUI(this, "add", null)).
                    setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane, 
                    "Status Pemustaka Tidak Aktif. \n Tidak Dapat Melakukan Pengusulan");
        }
        else
            JOptionPane.showMessageDialog(rootPane, 
                    "Maaf, Editor Hanya Bisa Satu Dalam Satu Waktu");
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnTambahActionPerformed(null);
    }//GEN-LAST:event_btnTambahKeyPressed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(instance == null)
        {
            if(tableShow.getSelectedRow() != -1)
            {
                ArrayList<String> data = new ArrayList<>();

                for(int i = 0; i < tableModel.getColumnCount(); i++)
                {
                    data.add(tableModel.getValueAt(tableShow.getSelectedRow(), i).
                            toString());
                }

                (instance = new PengusulanBahanPustakaPopUI(this, "edit", data)).
                        setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(rootPane, 
                    "Silahkan Pilih Data Yang Ingin Diubah");
        }
        else
            JOptionPane.showMessageDialog(rootPane, 
                    "Maaf, Editor Hanya Bisa Satu Dalam Satu Waktu");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnUbahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUbahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnUbahActionPerformed(null);
    }//GEN-LAST:event_btnUbahKeyPressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tableShow.getRowCount() == 0)
            JOptionPane.showMessageDialog(rootPane, 
                    "Data Masih Kosong, Tidak Ada Yang Bisa Dihapus");
        else if(tableShow.getSelectedRow() != -1)
        {
            tableModel.removeRow(tableShow.getSelectedRow());
        }
        else
            JOptionPane.showMessageDialog(rootPane, 
                    "Silahkan Pilih Salah Satu Data Dari Tabel Terlebih Dahulu");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnHapusActionPerformed(null);
    }//GEN-LAST:event_btnHapusKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            btnSimpanActionPerformed(null);
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(instance != null)
            JOptionPane.showMessageDialog(rootPane, "Silahkan Selesaikan Entri "
                    + "atau Edit Usulan Bahan Pustaka Pada Form Yang Aktif");
        else if(tableShow.getRowCount() != 0)
        {
            int pil = JOptionPane.showConfirmDialog(rootPane,
                    "Apakah Anda Yakin Untuk Menyimpan Usulan Bahan Pustaka ?", 
                    "Konfirmasi Penyimpanan", JOptionPane.YES_NO_OPTION);

            if(pil == 0)
            {
                C.reservedUsulan((IdUsulan = C.getNewIDUsulan()), Integer.parseInt(noAnggota), 
                        labelTanggal.getText().trim());

                for(int i = 0; i < tableModel.getRowCount(); i++)
                {
                    C.insertNewDetilUsulan(IdUsulan, tableModel.getValueAt(i, 0).toString(), 
                            tableModel.getValueAt(i, 1).toString(), 
                            tableModel.getValueAt(i, 2).toString(), 
                            tableModel.getValueAt(i, 3).toString(), IdProdi);
                }

                JOptionPane.showMessageDialog(rootPane, "Usulan Anda Berhasil Disimpan");

                this.dispose();
            }
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Data Usulan Masih Kosong");
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        // TODO add your handling code here:
        btnSimpan.setBackground(Color.cyan);
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        // TODO add your handling code here:
        btnSimpan.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        btnTambah.setBackground(Color.green);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        btnTambah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseEntered
        // TODO add your handling code here:
        btnUbah.setBackground(Color.green);
    }//GEN-LAST:event_btnUbahMouseEntered

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        // TODO add your handling code here:
        btnUbah.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Color.red);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHapusMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengusulanBahanPustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengusulanBahanPustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengusulanBahanPustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengusulanBahanPustakaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengusulanBahanPustakaUI(namaAnggota, noAnggota, katPem, 
                        prodi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JTable tableShow;
    private javax.swing.JTextField txtKatPem;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoAnggota;
    private javax.swing.JTextField txtProdi;
    // End of variables declaration//GEN-END:variables
}